builds:
  - main: ./cli
    id: "cli"
    binary: ./bin/sos
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}
    flags:
      - -mod=vendor
    ignore:
      - goos: windows
        goarch: arm64

  - main: ./verifier
    id: "verifier"
    binary: ./bin/verifier
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}
    flags:
      - -mod=vendor
    ignore:
      - goos: windows
        goarch: arm64

checksum:
  name_template: "checksums.txt"

nfpms:
  - package_name: sos-bin
    vendor: devlup-labs
    homepage: https://github.com/devlup-labs/sos
    maintainer: Saahil Bhavsar <saahil_bhavsar@outlook.com>
    license: MIT
    formats:
      - deb
      - archlinux
    release: "1"
    bindir: /usr
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/sos/LICENSE
      - src: README.md
        dst: /usr/share/doc/sos/README.md
      - src: ./scripts/configure-sos-server.sh
        dst: /etc/sos/scripts/configure-sos-server.sh

release:
  prerelease: auto
  github:
    owner: devlup-labs
    name: sos
  name_template: "{{.ProjectName}}-v{{.Version}}"
  extra_files:
    - glob: scripts/configure-sos-server.sh
    - glob: */bin/verifier*

aurs:
  - name: sos-bin
    homepage: https://github.com/devlup-labs/sos
    license: MIT
    maintainers:
      - "Saahil Bhavsar <saahil_bhavsar@outlook.com>"
    contributors:
      - "Saahil Bhavsar <saahil_bhavsar@outlook.com>"
      - "Jyotin Goel <b22ai063@iitj.ac.in>"
    commit_author:
      name: SaahilNotSahil
      email: saahil_bhavsar@outlook.com
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/sos-bin.git"
    package: |-
      install -Dm755 "./bin/verifier" "${pkgdir}/etc/sos/bin/verifier"
      install -Dm755 "./bin/sos" "${pkgdir}/usr/bin/sos"
      install -Dm755 "./scripts/configure-sos-server.sh" "${pkgdir}/etc/sos/scripts/configure-sos-server.sh"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/sos/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/sos/README.md"

archives:
  - wrap_in_directory: false
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - scripts/*
