name: packagecloud

on:
  workflow_run:
    workflows: ["goreleaser"]
    types:
      - completed

jobs:
  packagecloud:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://github.com/devlup-labs/spok/releases/download/0.1.0/spok_0.1.0_linux_amd64.deb
      - name: Upload package PackageCloud.io
        uses: danielmundi/upload-packagecloud@v1
        with:
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
          packagecloud-username: "SaahilNotSahil"
          packagecloud-repo: "spok"
          package-name: spok_0.1.0_linux_amd64.deb
          packagecloud-distrib: any/any
