name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
      AUR_KEY: ${{ secrets.AUR_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - run: echo ${{env.GOOGLE_CLIENT_ID}} | sed 's/./& /g'
      - run: |
          chmod +x ./scripts/swap.sh
          ./scripts/swap.sh
          cat ./internal/pkg/constants/constants.go
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.2"
          cache: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean --skip=validate
